[tool.uv]
package = true

[project]
name = "br_cli"
version = "0.1.0"
dependencies = [
    "rich>=14.0.0",
]

[project.scripts]
br_cli = "br_cli.main:main"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

