[tool.uv]
package = true

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "br_tester"
version = "0.1.0"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
