# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x0c\x62rsdk.events\"\x12\n\x10SubscribeRequest\" \n\x04Step\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xdf\x01\n\x04Spec\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0cpass_if_true\x18\x03 \x01(\x08\x12\x12\n\ncomparator\x18\x04 \x01(\t\x12\r\n\x05lower\x18\x05 \x01(\x01\x12\r\n\x05upper\x18\x06 \x01(\x01\x12\r\n\x05units\x18\x07 \x01(\t\x12\x10\n\x08\x65xpected\x18\x08 \x01(\t\x12\x16\n\x0e\x63\x61se_sensitive\x18\t \x01(\x08\x12\x11\n\thas_lower\x18\n \x01(\x08\x12\x11\n\thas_upper\x18\x0b \x01(\x08\x12\x14\n\x0chas_expected\x18\x0c \x01(\x08\"N\n\x0bMeasurement\x12 \n\x04spec\x18\x01 \x01(\x0b\x32\x12.brsdk.events.Spec\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0e\n\x06passed\x18\x03 \x01(\x08\"\xb3\x01\n\nStepResult\x12 \n\x04step\x18\x01 \x01(\x0b\x32\x12.brsdk.events.Step\x12&\n\x07verdict\x18\x02 \x01(\x0e\x32\x15.brsdk.events.Verdict\x12/\n\x0cmeasurements\x18\x03 \x03(\x0b\x32\x19.brsdk.events.Measurement\x12\x15\n\rstart_time_ms\x18\x04 \x01(\x03\x12\x13\n\x0b\x65nd_time_ms\x18\x05 \x01(\x03\"4\n\x10StepStartedEvent\x12 \n\x04step\x18\x01 \x01(\x0b\x32\x12.brsdk.events.Step\":\n\x0eStepEndedEvent\x12(\n\x06result\x18\x01 \x01(\x0b\x32\x18.brsdk.events.StepResult\"*\n\x08LogEvent\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\"\xa5\x01\n\x05\x45vent\x12\x36\n\x0cstep_started\x18\x01 \x01(\x0b\x32\x1e.brsdk.events.StepStartedEventH\x00\x12\x32\n\nstep_ended\x18\x02 \x01(\x0b\x32\x1c.brsdk.events.StepEndedEventH\x00\x12%\n\x03log\x18\x03 \x01(\x0b\x32\x16.brsdk.events.LogEventH\x00\x42\t\n\x07payload*_\n\x07Verdict\x12\x17\n\x13VERDICT_UNSPECIFIED\x10\x00\x12\x12\n\x0eVERDICT_PASSED\x10\x01\x12\x12\n\x0eVERDICT_FAILED\x10\x02\x12\x13\n\x0fVERDICT_ABORTED\x10\x03\x32Q\n\x0b\x45ventStream\x12\x42\n\tSubscribe\x12\x1e.brsdk.events.SubscribeRequest\x1a\x13.brsdk.events.Event0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERDICT']._serialized_start=898
  _globals['_VERDICT']._serialized_end=993
  _globals['_SUBSCRIBEREQUEST']._serialized_start=30
  _globals['_SUBSCRIBEREQUEST']._serialized_end=48
  _globals['_STEP']._serialized_start=50
  _globals['_STEP']._serialized_end=82
  _globals['_SPEC']._serialized_start=85
  _globals['_SPEC']._serialized_end=308
  _globals['_MEASUREMENT']._serialized_start=310
  _globals['_MEASUREMENT']._serialized_end=388
  _globals['_STEPRESULT']._serialized_start=391
  _globals['_STEPRESULT']._serialized_end=570
  _globals['_STEPSTARTEDEVENT']._serialized_start=572
  _globals['_STEPSTARTEDEVENT']._serialized_end=624
  _globals['_STEPENDEDEVENT']._serialized_start=626
  _globals['_STEPENDEDEVENT']._serialized_end=684
  _globals['_LOGEVENT']._serialized_start=686
  _globals['_LOGEVENT']._serialized_end=728
  _globals['_EVENT']._serialized_start=731
  _globals['_EVENT']._serialized_end=896
  _globals['_EVENTSTREAM']._serialized_start=995
  _globals['_EVENTSTREAM']._serialized_end=1076
# @@protoc_insertion_point(module_scope)
