[tool.uv]
package = true

[project]
name = "br_sdk"
version = "0.1.0"
dependencies = [
    "grpcio>=1.65.1",
    "grpcio-tools>=1.65.1",
    "pydantic>=2.11.4",
    "pyyaml>=6.0.2",
]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
